### PR TITLE
gets all jobs from api and performs upsert

### PR DESCRIPTION
**Pull request by rockerben**
changed findwork to get all 'data engineer' jobs, and then saves it to postgres

### CODE REVIEW

**Review by JesSchattschneider — APPROVED** [review]
great work!

**Comment by ZhiwenSong1** [comment]
Hi Team,

I need your help with git. Following on yesterday's conflicts, right now my
new branch (transform_emily) git push to my previous branch (extract_emily)
instead of main.
I've made quite a lot of changes tonight including one of the changes in
findwork.py in the pipelines folder and tested it works.

Cheers,

Emily

**Comment by rockerben** [comment]
Hi Emily,

Happy to help. :)

To push your new branch transform_emily to a new remote branch with the
same name (instead of pushing it to your previous branch extract_emily),
you need to explicitly specify the branch name when you push. Here are the
steps:

1. Ensure you are on the correct branch:

*git branch  * - You should see * transform_emily indicating you are
currently on the transform_emily branch.
If not, switch to it:
*git checkout transform_emily*

2. Push the local branch to a new remote branch with the same name:

*git push origin transform_emily*


*Explanationgit checkout -b transform_emily*: This command creates a new
branch named transform_emily and switches to it. If you already have this
branch, just ensure you are on it with git checkout transform_emily.
*git push origin transform_emily*: This command pushes the transform_emily
branch to the remote repository under the same name.

By explicitly specifying the branch name during the push, you ensure that
transform_emily is pushed as a new branch on the remote repository, and it
does not interfere with extract_emily or any other branch.

PS.
In my opinion I would discourage you guys from using *rebase, *
this video explains why:

https://www.youtube.com/watch?v=e9lnsKot_SQ

regards,
Ben

**Comment by rockerben** [comment]
Sending the correct link:

*Git MERGE vs REBASE: Everything You Need to Know*

https://www.youtube.com/watch?v=0chZFIZLR_0&list=RDCMUCZgt6AzoyjslHTC9dz0UoTw&index=2

*Rebasing vs. Merging*
Rebasing and merging are two different strategies for integrating changes
from one branch into another. Here's a brief comparison:

*Merging: *Creates a merge commit that joins the divergent branches,
preserving the commit history of both branches. This results in a more
accurate representation of the project's history but can create a more
cluttered commit history.

*Rebasing:* Rewrites the commit history of the feature branch by moving the
branch's base to the latest commit on the branch it's rebased onto. This
results in a linear commit history, making it easier to understand the
project's timeline. However, it changes the commit history of the feature
branch, which can cause problems if the branch has already been shared with
others.


*Reasons Rebasing May Be Discouraged**Loss of Commit History:* Rebasing
rewrites commit history, which can make it difficult to track changes and
understand the development timeline, especially in shared branches where
multiple collaborators are working.

*Potential for Conflict:* Rebasing can lead to conflicts if the same
changes have been made in both branches. Resolving conflicts during a
rebase can be more complex than during a merge.

*Shared Branches:* Rebasing is not recommended for branches that are shared
with others, as it changes the commit history. It can cause confusion and
make it harder for collaborators to follow changes.

*Complexity:* While rebasing can result in a cleaner commit history, it
requires a good understanding of Git and can be more complex to manage,
especially for beginners.

*When to Use Rebasing*
Rebasing is generally more suitable for:

Feature branches that have not been shared with others.
Cleaning up the commit history before merging changes into the main branch.
Keeping a clean and linear history for individual feature branches.


*Conclusion*Rebasing is a powerful tool in Git, but it should be used with
caution and an understanding of its implications. While it can create a
cleaner commit history, it may not always be the best choice, especially
for shared branches or in situations where preserving the original commit
history is important. It's essential to weigh the benefits and drawbacks
and choose the appropriate strategy for your specific use case.

(source: ChatGPT)

**Comment by ZhiwenSong1** [comment]
Hi Ben,

I managed sloving the conflicts in the commandline. Here is the
instruction.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

Good learning experience. Now all my latest changes are in Main. Please do
a git pull before working on it.

Cheers,

Emily

**Pull request merged**
