### PR TITLE
Feature/add database connection

### PR DESCRIPTION
**Pull request by JesSchattschneider**

### CODE REVIEW

**Comment by rockerben** [comment]
Nicely done Jess!

**Comment by ZhiwenSong1** [comment]
Hi Ben,I will be 1 hour late for our catch up. What’s the meeting room?Cheers,Emily发自我的 iPhone在 2024年5月26日，上午5:18，Ben Cortez ***@***.***> 写道：﻿
Nicely done Jess!

**Comment by rockerben** [comment]
That's ok, lets meet at 1pm Sydney then so I can get organized :)

https://meet.google.com/oon-bimk-iok

**Review by rockerben — COMMENTED** [review]
changes have been reviewed. lgtm.

**Comment by ZhiwenSong1** [comment]
Hi,

I finally get online now. Let me see what we are up to now.

Cheers,

Emily

**Comment by ZhiwenSong1** [comment]
Hi Guys,

I've added the transform part into our repository. However, we do need some
other columns in the source table such as datetime, employment_type and
remote. Lets' have a discussion tomorrow.

Thanks.

Cheers,

Emily

**Pull request merged**
